//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BulkSmsRoutine.WebRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="sms_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/sms")]
    public partial class sms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MarkSmsAsSentOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnGetSavedBulkMsgOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnSaveBulkSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback FnMarkBulkSmsAsSentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public sms() {
            this.Url = global::BulkSmsRoutine.Properties.Settings.Default.BulkSmsRoutine_WebRef_sms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MarkSmsAsSentCompletedEventHandler MarkSmsAsSentCompleted;
        
        /// <remarks/>
        public event FnGetSavedBulkMsgCompletedEventHandler FnGetSavedBulkMsgCompleted;
        
        /// <remarks/>
        public event FnSaveBulkSMSCompletedEventHandler FnSaveBulkSMSCompleted;
        
        /// <remarks/>
        public event FnMarkBulkSmsAsSentCompletedEventHandler FnMarkBulkSmsAsSentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/sms:MarkSmsAsSent", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", ResponseElementName="MarkSmsAsSent_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MarkSmsAsSent(int entryNo) {
            this.Invoke("MarkSmsAsSent", new object[] {
                        entryNo});
        }
        
        /// <remarks/>
        public void MarkSmsAsSentAsync(int entryNo) {
            this.MarkSmsAsSentAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void MarkSmsAsSentAsync(int entryNo, object userState) {
            if ((this.MarkSmsAsSentOperationCompleted == null)) {
                this.MarkSmsAsSentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarkSmsAsSentOperationCompleted);
            }
            this.InvokeAsync("MarkSmsAsSent", new object[] {
                        entryNo}, this.MarkSmsAsSentOperationCompleted, userState);
        }
        
        private void OnMarkSmsAsSentOperationCompleted(object arg) {
            if ((this.MarkSmsAsSentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarkSmsAsSentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/sms:FnGetSavedBulkMsg", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", ResponseElementName="FnGetSavedBulkMsg_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnGetSavedBulkMsg(int entryId) {
            object[] results = this.Invoke("FnGetSavedBulkMsg", new object[] {
                        entryId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnGetSavedBulkMsgAsync(int entryId) {
            this.FnGetSavedBulkMsgAsync(entryId, null);
        }
        
        /// <remarks/>
        public void FnGetSavedBulkMsgAsync(int entryId, object userState) {
            if ((this.FnGetSavedBulkMsgOperationCompleted == null)) {
                this.FnGetSavedBulkMsgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnGetSavedBulkMsgOperationCompleted);
            }
            this.InvokeAsync("FnGetSavedBulkMsg", new object[] {
                        entryId}, this.FnGetSavedBulkMsgOperationCompleted, userState);
        }
        
        private void OnFnGetSavedBulkMsgOperationCompleted(object arg) {
            if ((this.FnGetSavedBulkMsgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnGetSavedBulkMsgCompleted(this, new FnGetSavedBulkMsgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/sms:FnSaveBulkSMS", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", ResponseElementName="FnSaveBulkSMS_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnSaveBulkSMS(string bulkSMSText) {
            object[] results = this.Invoke("FnSaveBulkSMS", new object[] {
                        bulkSMSText});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnSaveBulkSMSAsync(string bulkSMSText) {
            this.FnSaveBulkSMSAsync(bulkSMSText, null);
        }
        
        /// <remarks/>
        public void FnSaveBulkSMSAsync(string bulkSMSText, object userState) {
            if ((this.FnSaveBulkSMSOperationCompleted == null)) {
                this.FnSaveBulkSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnSaveBulkSMSOperationCompleted);
            }
            this.InvokeAsync("FnSaveBulkSMS", new object[] {
                        bulkSMSText}, this.FnSaveBulkSMSOperationCompleted, userState);
        }
        
        private void OnFnSaveBulkSMSOperationCompleted(object arg) {
            if ((this.FnSaveBulkSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnSaveBulkSMSCompleted(this, new FnSaveBulkSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/sms:FnMarkBulkSmsAsSent", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", ResponseElementName="FnMarkBulkSmsAsSent_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/sms", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string FnMarkBulkSmsAsSent(int entryNo) {
            object[] results = this.Invoke("FnMarkBulkSmsAsSent", new object[] {
                        entryNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FnMarkBulkSmsAsSentAsync(int entryNo) {
            this.FnMarkBulkSmsAsSentAsync(entryNo, null);
        }
        
        /// <remarks/>
        public void FnMarkBulkSmsAsSentAsync(int entryNo, object userState) {
            if ((this.FnMarkBulkSmsAsSentOperationCompleted == null)) {
                this.FnMarkBulkSmsAsSentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFnMarkBulkSmsAsSentOperationCompleted);
            }
            this.InvokeAsync("FnMarkBulkSmsAsSent", new object[] {
                        entryNo}, this.FnMarkBulkSmsAsSentOperationCompleted, userState);
        }
        
        private void OnFnMarkBulkSmsAsSentOperationCompleted(object arg) {
            if ((this.FnMarkBulkSmsAsSentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FnMarkBulkSmsAsSentCompleted(this, new FnMarkBulkSmsAsSentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void MarkSmsAsSentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FnGetSavedBulkMsgCompletedEventHandler(object sender, FnGetSavedBulkMsgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnGetSavedBulkMsgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnGetSavedBulkMsgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FnSaveBulkSMSCompletedEventHandler(object sender, FnSaveBulkSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnSaveBulkSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnSaveBulkSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void FnMarkBulkSmsAsSentCompletedEventHandler(object sender, FnMarkBulkSmsAsSentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FnMarkBulkSmsAsSentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FnMarkBulkSmsAsSentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591